### PR TITLE
Allow Telegram Thread/Topic

### PR DESCRIPTION
**Pull request by luc-ass**
Hi @rabilrbl,

I have added topics/threads to the main repository. Do you think I forgot something? The way I built it is compatible with the environment variable you chose - seems like that was intuitive ;)

Cheers, Lucas

### CODE REVIEW

**Comment by rabilrbl** [comment]
Hi @luc-ass,

These are some quick dirty commits I made to support topics, but they get the job done 😄. 

I think you're all set to merge, and I didn't see anything that needed additional work. 

I've been using my forked version daily, and it's been working seamlessly for me!

**Comment by luc-ass** [comment]
Great! Mind giving the original a test without changing your environment variables? From what I can see, everything should be in place already ;)

**Comment by rabilrbl** [comment]
> Great! Mind giving the original a test without changing your environment variables? From what I can see, everything should be in place already ;)

If you meant without providing topic id env var, yes it works.

**Comment by luc-ass** [comment]
Sorry, I'll try to be more precise. 

- try to only replace the image with the latest version of `lorcas/docker-telegram-notifier`
- keep your environment variable `TELEGRAM_NOTIFIER_TOPIC_ID`

v1.4.2 should handle that correctly

**Comment by rabilrbl** [comment]
Yes, it works fine

**Comment by luc-ass** [comment]
Great! I'll then close this pull request without merging, as this feature already exists (and allows you to set topic_id per monitored container). Thank you for testing! Let me know if you think this project could be enhanced in other ways.

**Comment by luc-ass** [comment]
→ added you to the contributors here b8492de13fdc2138049667de94db7ab04f40e4a0. Thanks again for helping! 🚀 🚀

**Pull request closed without merging**
