### PR TITLE
How-to customize template.js and fully leverages dockerode with customizable connect text

### PR DESCRIPTION
**Pull request by oliveratgithub**
* Added detailed how-to customize `template.js` messages, including available event variables
* Fixed the broken GitHub-workflow badge status in the README
* Added more [Docker- and Host related variables](https://docs.docker.com/reference/api/engine/version/v1.37/#tag/System/operation/SystemInfo) to connect text via `dockerode`
* Removed the dependency of `require('os')` as data is part of `dockerode` already (see above point)
* Made the connect notification message customizable via `template.js`

**REMARKS**

Unfortunately I am not able to test these changes, so would appreciate if someone could do so before merging.

Also I am not really familiar with node.js development, and mostly did the changes by adapting to the existing code, with help of the official Docker Engine API and dockerode documentations.

### CODE REVIEW

**Comment by luc-ass** [comment]
Hey there, thank you for taking part in this project! The changes you made look promising. I'll try to test them over the next few days.

**Review by luc-ass — APPROVED** [review]

**Comment by luc-ass** [comment]
I'll merge it into the current development branch. Let's see how it goes ;)

**Comment by oliveratgithub** [comment]
> I'll merge it into the current development branch. Let's see how it goes ;)

@luc-ass seems to work - tested with `lorcas/docker-telegram-notifier:v1.4.0-beta3` 😎

Connection info I get via Telegram Bot message:

```
Connected to docker v27.3.1 on orbstack
OS: linux/aarch64 (OrbStack), 10 CPU, 20033.24MB RAM
```

**Comment by luc-ass** [comment]
Same here! Great addition!

**Pull request merged**
